### PR TITLE
Advent of Code rust

### PR DESCRIPTION
**Pull request by LD250**
Hello @ctjhoa ,
Now I have work in progress of finishing http://adventofcode.com/ puzzles using rust.
I have a plan to do all the puzzles from 11 through 25.
Not sure if I am using "rust best practice" there, but maybe this will come in handy for Rust learners.

### CODE REVIEW

**Comment by ctjhoa** [comment]
Thanks @LD250 
I haven't test it yet but it seems cover programming  in general more than rust specifically.
Am I right ?

**Comment by LD250** [comment]
Yes. Its a general programming problems solved with rust.
I saw something similar in your repo, Project Euler (https://github.com/gifnksm/ProjectEulerRust).

So if the Project Euler solved with rust is good to be shown here, maybe the Advent of Code solved with rust will be good to show too.

**Comment by LD250** [comment]
Here is the the link to the repo for quick access https://github.com/LD250/adventofcode_rust

**Comment by ctjhoa** [comment]
@LD250 sorry I've been really busy. Seems ok to merge to me.

Hint: Your code doesn't seems to be idiomatic rust code, maybe try to use rustfmt and/or to post it on rust forum or reddit for improvement.
Anyway, thanks!

**Comment by LD250** [comment]
@ctjhoa thank you for the advise. I will try rustfmt.

**Pull request merged**
