### PR TITLE
Update README.md - Added intro to Rust using permission-based authorization example

### PR DESCRIPTION
**Pull request by Dowwie**

### CODE REVIEW

**Comment by ctjhoa** [comment]
Sorry for the delay but I have doubt about the utility and the clarity of this guide. I'm not convinced that exploring such a lib is good way of learning rust. Is it yours or did you find it useful and want to share this link with others?

**Comment by Dowwie** [comment]
I am the author.  You have doubts about the utility and clarity?  Thanks for the feedback.  I learn by example, as do others.  Are you the only person to authorize changes to this repo and what are your credentials?

**Comment by eliukblau** [comment]
The guide seems to be fine for me. Exactly as is: a guide. Not a course or tutorial.

**Comment by ctjhoa** [comment]
Ok so there is multiple things going on here and I will try to answer as best as I can to each of them.

1- This PR has been open without any words in it. So there was no explanation about why this addition could benefits to the community. I follow actively /r/rust and I didn't saw that link neither.

2- I said "I have doubts" doesn't mean that I'm totally oppose to this addition. Otherwise I would have closed this PR immediately. That why I asked you more details.

3- This repo is open to the community and as every open community it's need moderation. Mine is surely not perfect but I try to do my best. I've already merge more than hundred PRs no one ever complained. As the rust community evolve and becomes bigger and bigger a lot articles pop out and I will be more demanding. The goal is not to provides links that repeat the same content as "The Rust Programming Language" book over and over again. That's what I'm referring talking about "utility" (in community scope of course).

4- It's nothing personal, it's just that I want to take the best out the community. If you think that my judgment is wrong you can become an active reviewer.

5- About the contributing guide, I didn't have time to write one yet but I agree with that. This one should cover all the formatting things and some rules about accepting links (something like https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md). You can open a PR on that I'll be happy to discuss about it and merge it.

6- I will read again your whole guide to get a fresh look at it.

**Comment by ctjhoa** [comment]
I've finally decide to merge this. I have also create contribution guideline.
@Dowwie @eliukblau Feel free to become maintainers.

**Pull request merged**
