### PR TITLE
Added “release date” for each video

### PR DESCRIPTION
**Pull request by cento**
Added “release date” for each video, ordered in descending order (recent first).
Issue #98

### CODE REVIEW

**Comment by ctjhoa** [comment]
Could you respect the format describe in #98 please? Thanks

**Comment by cento** [comment]
Is the day necessary?

**Comment by ctjhoa** [comment]
I'm still unsure about the format because I fear a polution of the wiki by this format.
What do you think about keeping the sort but do not display dates?
This way, recent resources should be hightlight without boilerplate.

**Comment by cento** [comment]
I don't know, because the release date for video is a form of pollution, but it is useful for a language like Rust that is constantly evolving. Let me think.

**Comment by ctjhoa** [comment]
Of course the idea is to add a note about this sorting on the top of the page.

**Comment by ctjhoa** [comment]
@cento so what's your feedback on this?

**Comment by cento** [comment]
I think we should keep the data for videos as you initially suggested because watching a video requires more efforts in term of time and the final user could be interested in spending this time with the most recent contribution. Or, at least, this happens to me when I study a new language.

**Comment by ctjhoa** [comment]
@cento @ayush000 I have finally time to work on this. I kept the same idea plus some refactoring in this commit 4796b01a8a5dcb2a09da285c743f028c6efdcdf9

Thanks for your patience.

**Pull request closed without merging**
