### PR TITLE
Add more Spanish links

### PR DESCRIPTION
**Pull request by AdrianArroyoCalle**

### CODE REVIEW

**Comment by eliukblau** [comment]
The second link ("La gestión de la memoria en Rust") is very poorly translated, e.g. word "membresía" meaning "borrow" (the proper spanish word for that is "préstamo"). In spanish, "membresía" means "membership". I don't recommend add this link. Sorry.

**Comment by AdrianArroyoCalle** [comment]
Ok. I'm the author of that post so I can change it now.

2016-12-27 7:49 GMT+01:00 Eliuk Blau <notifications@github.com>:

**Comment by ctjhoa** [comment]
@AdrianArroyoCalle keep me and @eliukblau in touch

**Comment by AdrianArroyoCalle** [comment]
Updated, check it now

2016-12-27 18:54 GMT+01:00 Camille TJHOA <notifications@github.com>:

**Comment by eliukblau** [comment]
@ctjhoa both articles looks fine now, thanks @AdrianArroyoCalle

**Comment by ctjhoa** [comment]
Thank you both and happy new year!

**Pull request merged**
